### ISSUE TITLE
Some foods, for example Horse Steak gives x103 Saturation

### ISSUE THREAD

**Issue by Gbergz** [EPIICTHUNDERCAT/ImmersiveFood-OfficalPort#2]
Title^

Is it supposed to be like this?
& some Raw meats give the same saturation as a normal vanilla steak for example.
Im using the latest version for 1.12.1
"v0.0.2"

Screenshot & GIF:
[Screenshot](https://i.imgur.com/ZqdxdDx.png)
[GIF](https://gfycat.com/AggravatingReadyDogwoodtwigborer)

**Comment by EPIICTHUNDERCAT** [comment]
I believe Initially I wanted the foods to be more powerful than vanilla foods to make them something people sought after, this was of course with just this mod being installed. I believe I made food values customizable however, so the player has the option to change it if it is an issue for them. Ill look again

**Comment by EPIICTHUNDERCAT** [comment]
Okay I only made drops configurable, I Can add a config to Food saturations.

**Comment by EPIICTHUNDERCAT** [comment]
fixed in new versions.
